name = "rt-nova-website"
compatibility_date = "2026-06-12"
workers_dev = true
preview_urls = true

[build]
command = "./build.sh"

[assets]
directory = "./public"
html_handling = "auto-trailing-slash"
not_found_handling = "404-page"
run_worker_first = false
